include (FindPackageHandleStandardArgs)
include (CheckFunctionExists)

find_path(BLOCKSRUNTIME_PUBLIC_INCLUDE_DIR Block.h
  DOC "Path to Block.h"
)

if (BLOCKSRUNTIME_PUBLIC_INCLUDE_DIR)
  list (APPEND BLOCKSRUNTIME_INCLUDE_DIRS ${BLOCKSRUNTIME_PUBLIC_INCLUDE_DIR})
endif ()

find_path(BLOCKSRUNTIME_PRIVATE_INCLUDE_DIR Block_private.h
  DOC "Path to Block_private.h"
)
if (BLOCKSRUNTIME_PRIVATE_INCLUDE_DIR)
  list (APPEND BLOCKSRUNTIME_INCLUDE_DIRS ${BLOCKSRUNTIME_PRIVATE_INCLUDE_DIR})
  set (BLOCKSRUNTIME_PRIVATE_HEADERS_FOUND TRUE)
endif ()

check_function_exists(BLOCKSRUNTIME_RUNTIME_IN_LIBC _Block_copy)
if (NOT BLOCKSRUNTIME_RUNTIME_IN_LIBC)
  find_library(BLOCKSRUNTIME_LIBRARIES "BlocksRuntime")
endif ()

if (BLOCKSRUNTIME_LIBRARIES OR BLOCKSRUNTIME_RUNTIME_IN_LIBC)
  set (FOUND_BLOCKSRUNTIME 1)
else ()
  set (FOUND_BLOCKSRUNTIME 0)
endif()

find_package_handle_standard_args(BlocksRuntime
  REQUIRED_VARS FOUND_BLOCKSRUNTIME BLOCKSRUNTIME_PUBLIC_INCLUDE_DIR)

